config/routes.rb
Rails.application.routes.draw do
  get 'sitemap.xml.gz', :to => 'sitemap#index', :defaults => {:format => 'xml'}
   #get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-1.amazonaws.com/danielpilates/sitemap.xml.gz")
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'welcome#index'
    get 'welcome/about'
    devise_for :admins
    resources :products
    resources :posts
    resources :contacts, only: [:new, :create]
    resources :charges

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  translates :title, :main_title, :sub_title, :image, :description, :slug
  extend FriendlyId
  friendly_id :title, use: [:globalize, :history, :slugged]
  globalize_accessors locales: [:en, :es, :he, :de], attributes: [:title, :main_title, :sub_title, :image, :description, :slug]
    def normalize_friendly_id(input)
     input.gsub(".", "").to_slug.to_s
    end
    def should_generate_new_friendly_id?
      attribute_changed?('title')
    end
    
    has_attached_file :image, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :main_title, :sub_title, :image, :description, :sluge)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :main_title %>
    <%= form.text_field :main_title, id: :post_main_title %>
  </div>

  <div class="field">
    <%= form.label :sub_title %>
    <%= form.text_field :sub_title, id: :post_sub_title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :post_image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<br>
<br>
<!-- Page Content -->
    <div class="container">

      <!-- Page Heading/Breadcrumbs -->
      <h1 class="mt-4 mb-3">
        <small></small>
      </h1>

      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="index.html">Home</a>
        </li>
        <li class="breadcrumb-item active">Blog Home 2</li>
      </ol>
       
      <!-- Blog Post -->
      <% @posts.each do |post| %>
      <div class="card mb-4">
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <% link_to post do %>
              <%= image_tag post.image, class: "card-img-top"%>
               <% end %>
            </div>
            <div class="col-lg-6">
              <h2 class="card-title"><%= post.main_title %></h2>
              <p class="card-text"><%= post.sub_title %></p>
              <%= link_to 'Read More', post, class: 'btn btn-primary' %>
              <% if admin_signed_in? %>
                <%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary" %>
                <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
                <%= link_to 'New Post', new_post_path, class: "btn btn-primary" %>
              <% end %>
              </div>
          </div>
        </div>
        <div class="card-footer text-muted">
          Posted on <%= post.created_at.strftime("%B %d %Y, %l:%M%P") %>
        </div>
      </div>
      <% end%></div>
  <!-- Footer -->
  <footer class="py-5 bg-light">
    <div class="container">
      <p class="m-0 text-center text-black">Copyright &copy; Your Website 2018</p>
    </div>
    <!-- /.container -->
</footer>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container"><div>
        <%= link_to I18n.with_locale(:en){post_path(@post, locale: 'en')} do %>
          <%= image_tag('https://pilatesshopa.s3-eu-west-1.amazonaws.com/posts/images/000/000/001/original/usa.png?1520004588', width: '23', height: '15.33', alt: 'English') %>
        <% end %>
        <%= link_to I18n.with_locale(:es){post_path(@post, locale: 'es')} do %>
          <%= image_tag('https://pilatesshopa.s3-eu-west-1.amazonaws.com/products/images/000/000/001/original/spain.png?1520005015', width: '23', height: '15.33', alt: 'English') %>
        <% end %>
        <%= link_to I18n.with_locale(:he){post_path(@post, locale: 'he')} do %>
          <%= image_tag('https://dbcdnk728du6i.cloudfront.net/teams/logos/128x128/2713-israel.png', width: '23', height: '15.33', alt: 'English') %>
        <% end %>
        <%= link_to I18n.with_locale(:de){post_path(@post, locale: 'de')} do %>
          <%= image_tag('https://cdn3.iconfinder.com/data/icons/world-flags-square-vol-2/48/Germany-128.png', width: '23', height: '15.33', alt: 'English') %>
        <% end %></div>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to t('navbar.blog'), posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to t('navbar.products'), products_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to t('navbar.about'), welcome_about_path, class: "nav-link" %>
            <li>
            <li class="nav-item">
              <%= link_to t('navbar.contact'), new_contact_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <% if admin_signed_in? %>
                <%= link_to "Sign Out", destroy_admin_session_path, method: :delete, class: "nav-link" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

        <!-- Page Content -->
    <div class="container">

      <!-- Page Heading/Breadcrumbs -->
      <h1><%= @post.main_title %></h1>
     

      

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Preview Image 900x300-->

         <%= image_tag @post.image.url, class: "img-fluid rounded" %>


          <hr>

          <!-- Date/Time -->
          <h2><%= @post.sub_title %></h2>

          <hr>

          <!-- Post Content -->
          <p class="lead"><%= raw @post.description %></p>

          
         <p>Posted on <%= @post.created_at.strftime("%B %d %Y, %l:%M%P") %></p>
          
        
          <center>
          <a class="twitter-share-button" href="https://twitter.com/donpilates/">Tweet</a>
          <a class="twitter-follow-button"
          href="https://twitter.com/TwitterDev">
          Follow @Donpilates</a>

          <!--<script src="https://apis.google.com/js/platform.js" async defer></script>
          <g:plusone></g:plusone>
          <script src="https://apis.google.com/js/platform.js" async defer></script>
          <g:plus action="share"></g:plus>-->
          
          </center>
          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
              agghg
              <% if admin_signed_in? %>
                  <%= link_to 'Edit', edit_post_path %>
              <% end %>
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    

     


      


    <!-- Footer -->
    <footer class="py-5 bg-light">
      <div class="container">
        <p class="m-0 text-center text-dark">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>