config/routes.rb
Rails.application.routes.draw do
  get 'sitemap.xml.gz', :to => 'sitemap#index', :defaults => {:format => 'xml'}
   #get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-1.amazonaws.com/danielpilates/sitemap.xml.gz")
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'welcome#index'
    get 'welcome/about'
    devise_for :admins
    resources :products
    resources :posts
    resources :contacts, only: [:new, :create]
    resources :charges

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  translates :title, :main_title, :sub_title, :image, :price, :description, :slug
  extend FriendlyId
  friendly_id :title, use: [:globalize, :history, :slugged]
  globalize_accessors locales: [:en, :es, :he, :de], attributes: [:title, :main_tile, :sub_title, :price, :description, :slug]
    def normalize_friendly_id(input)
     input.gsub(".", "").to_slug.to_s
    end
    def should_generate_new_friendly_id?
      attribute_changed?('title')
    end
     
 

  
  has_attached_file :image,
      :default_url => "/images/:style/missing.png",
      :storage => :s3,
      :s3_credentials => {
        :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
        :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'] },
      :url => ':s3_alias_url',
      :s3_host_alias => 'd36y0kv3zyrf84.cloudfront.net', 
      :bucket => 'danielpilates',
      use_timestamp: false

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :main_title, :sub_title, :image, :price, :description, :slug)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :main_title %>
    <%= form.text_field :main_title, id: :product_main_title %>
  </div>

  <div class="field">
    <%= form.label :sub_title %>
    <%= form.text_field :sub_title, id: :product_sub_title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :product_image %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<br>
<br>
<br>
<br>

<div class="container">
<h1 class="mt-4 mb-3">
<small></small>
</h1>
<div class="row">
<% @products.each do |product| %>
<div class="col-lg-4 col-sm-6 portfolio-item">
<div class="card h-100">
<%= link_to product do %>
<%= image_tag product.image,class: "card-img-top", alt: ""%>
<% end %>
<div class="card-body">
<h4 class="card-title">
<%= link_to product do %>
<%= product.main_title %>
<% end %>
</h4>
<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
<% if admin_signed_in? %>
<%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary" %>
<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
<%= link_to 'New Product', new_product_path, class: "btn btn-primary" %>
<% end %>
</div>
</div>
</div>
<% end %>
</div>
      






























    </div>
    <!-- /.container -->

     

    <!-- Footer -->
    <footer class="py-5 bg-light">
      <div class="container">
        <p class="m-0 text-center text-black">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<br>
<br>
<div class="container">
<h1 class="mt-4 mb-3"><%= @product.main_title %>
</h1>
<div class="row">
<div class="col-lg-8">
<%= image_tag @product.image, class: "img-fluid rounded", itemprop: "image" %>
<hr>
<p class="lead"><%= @product.description %></p>
<hr>

</div>
</div>    
</div>




<footer class="py-5 bg-light">
<div class="container">
<p class="m-0 text-center text-black">Copyright &copy; Your Website 2018</p>
</div>
</footer>